#!/usr/bin/env zsh

if [[ "${IS_WSL}" -eq 1 ]]; then
	echo "Detected WSL, Installing linux packages"

	sudo apt-get update && \
	sudo apt-get upgrade -y && \
	sudo apt-get dist-upgrade -y && \
	sudo apt-get install -y \
		keychain
fi
