cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/dupes'

brew 'bash'
brew 'coreutils'
brew 'findutils'
brew 'gnu-sed', args: ['default-names']
brew 'go'
brew 'grc'
brew 'grep'
brew 'hub'
brew 'imagemagick', args: ['with-webp']
brew 'jp2a'
brew 'libgit2'
brew 'moreutils'
brew 'node'
brew 'nvm'
brew 'openssh'
brew 'openssl'
brew 'readline'
brew 'roundup'
brew 'tmux'
brew 'unrar'
brew 'vim', args: ['override-system-vi']
brew 'wget', args: ['with-iri']
brew 'zopfli'

cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'garmin-express'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'gyazo'
cask 'handbrake'
cask 'hyperdock'
cask 'iterm2'
cask 'licecap'
cask 'limechat'
cask 'mapbox-studio'
cask 'rescuetime'
cask 'screenhero'
cask 'seashore'
cask 'slack'
cask 'steam'
cask 'sublime-text'
cask 'tunnelbear'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
